export const questions = [
  {
    id: 0,
    set: 1,
    type: 'slider',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  },
  {
    id: 1,
    set: 1,
    type: 'slider',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  },
  {
    id: 2,
    set: 1,
    type: 'radiobutton',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  },
  {
    id: 3,
    set: 1,
    type: 'radiobutton',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  },
  {
    id: 4,
    set: 1,
    type: 'radiobutton',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  },
  {
    id: 5,
    set: 1,
    type: 'slider',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  },
  {
    id: 6,
    set: 1,
    type: 'free text',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  },
  {
    id: 7,
    set: 1,
    type: 'free text',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  },
  {
    id: 8,
    set: 1,
    type: 'slider',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  },
  {
    id: 9,
    set: 1,
    type: 'multiple choice',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  },
  {
    id: 10,
    set: 1,
    type: 'multiple choice',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  },
  {
    id: 11,
    set: 1,
    type: 'slider',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  },
  {
    id: 12,
    set: 1,
    type: 'multiple choice',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  },
  {
    id: 13,
    set: 1,
    type: 'free text',
    title: 'A nice title',
    subtitle: 'A more descripte text about the question',
  }
]
